### ISSUE TITLE
Sidebar Position and more ...

### ISSUE THREAD

**Issue by WirthmU** [thomasjacquin/allsky-website#119]
In one of my cameras the sidebar covers the camera informations.
![image](https://user-images.githubusercontent.com/27740335/175490252-2c639020-60c9-4dd5-9af2-cc288a6ffe81.png)

Is there an easey way to move it out of the way?

Also in the AllSky information the intend for latitude and longitude does not line up with the others:
![image](https://user-images.githubusercontent.com/27740335/175491581-1d240484-d6a9-47c5-b301-7495289496a0.png)

**Comment by EricClaeys** [comment]
@WirthmU   The latitude and longitude not lining up is fixed in the next version of the website.  You'll also be able to specify the placement of the sidebar - the default is 150px down from the top of the screen.

In the meantime, the quick fix for the sidebar issue is to decrease the **Line Height** and/or **Font Size** in the WebUI so there isn't as much of a gap between lines.
OR
you can edit `/var/www/html/allsky/allsky.css` - look for **sidebar**, then `top: 150px` and change it to whatever you want.  This will get replaced when you update the website, but if it's the new version that'll be ok.

If this works for you, would you please close the Issue since it'll be fixed in the next version?
