### ISSUE TITLE
RFC - Step frame forward or backwards in the videos

### ISSUE THREAD

**Issue by calberts** [thomasjacquin/allsky-website#124]
A other RFC request of change I have which I think is more important is
to step forward or backwards on the frame level in the video.
It some times hard to find the right frame  with the meteor, iridium flare seen,  or other items which I like to capture
like  recently landed church owl ;-)

Chris

**Comment by EricClaeys** [comment]
@calberts   This is not something Allsky controls.  It's browser specific.  I haven't even found a video player on Linux or Windows that will do it.  I happen to have the full Adobe Suite which includes Photoshop and Premier, so I load a video into Premier and stop forward and back frame-by-frame.

I'm really surprised Windows media viewer and their newer viewer don't support frame-by-frame viewing.

Since this isn't an Allsky Issue, I'm closing this.
